# Generated by Django 3.0 on 2019-12-05 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
                ('cliente', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha Creación')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('rol', models.ManyToManyField(to='pedido.Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idGrupo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Componente')),
            ],
            options={
                'verbose_name': 'DetalleOrden',
                'verbose_name_plural': 'DetalleOrdenes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='componente',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.TipoComponente'),
        ),
    ]
